title: Desearch and Revelopment
encoding: UTF-8
description: >- # this means to ignore newlines until "baseurl:"
  Experiments in abstract thought and the theory of software engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: etscrivner
github_username:  etscrivner
google_analytics: UA-53339846-1
repository: "etscrivner/etscrivner.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-github

exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
